### ISSUE TITLE
Clean exit logic will prevent node from exiting after a SIGINT or SIGTERM

### ISSUE THREAD

**Issue by raulmt** [fadeenk/primus-rooms-redis-adapter#5]
When I enable cleanExit logic using the `options` function with a primus instance, I cannot terminate the node process by a SIGINT (ctrl-C in the terminal).

From [node documentation](https://nodejs.org/api/process.html#process_signal_events), it seems when you register a listener on SIGINT or SIGTERM (like what this module does [here](https://github.com/fadeenk/primus-rooms-redis-adapter/blob/master/lib/primus-rooms-redis-adapter.js#L307)), the default node listeners will be removed, and that means the process won't exit (and then you need to SIGKILL it).

I'm not sure about this, but it looks like we need a `process.exit()` call after [this line](https://github.com/fadeenk/primus-rooms-redis-adapter/blob/master/lib/primus-rooms-redis-adapter.js#L293) in a process.nextTick call. But to make it really correct, according to that node doc SIGINT and SIGTERM do a process.exit with a particular code (128 + signal) so this means we should have a way to identify the signal, which I think means changing code when creating the listeners [here](https://github.com/fadeenk/primus-rooms-redis-adapter/blob/master/lib/primus-rooms-redis-adapter.js#L307).

I can try sending a PR, but I wanted to first ask here if what I'm saying makes sense and would be a good approach.

**Comment by fadeenk** [comment]
I agree that is true. However it is like this by design.

The reasoning for that is the according to the [node documentation](https://nodejs.org/api/process.html#process_process_exit_code) the process will exit automatically when the event queue is empty. If the adapter forces the node process to exit without resolving the calls that are on the event queue, it will cause unexpected issues if the app has things to do onExit. 

The correct way to resolve this would be for you to identify what is holding up the event queue. This [package](https://github.com/myndzi/wtfnode) makes things easier to find out what it is. Also, assuming you are using the node http and/or express you might want to set the timeout (see [adapter.config note](https://github.com/fadeenk/primus-rooms-redis-adapter#adapterconfigoptions-cb)).

Hope this answers your question :)

**Comment by fadeenk** [comment]
Also I just noticed I dont have the proper documentation for what the adapter dose when it comes to the signal listeners.

**Comment by raulmt** [comment]
Ahh, thanks, I'll look further for the problem then… I thought it was this because ctrl-C will work if I don't pass primus (and thus adding these listeners), but maybe it was just making visible a problem in some other place…

**Comment by raulmt** [comment]
After looking about this, it turned out that, as you said, there was something else preventing the node process from having an empty event loop. Now I can close the app with ctrl-c having this clean exit logic active. Thanks @fadeenk !

**Comment by fadeenk** [comment]
Anytime :)
